 mutation updatePlantBrand(
        $plantInfoId:Int,
        $plantId:Int,
        $brandId:[Int]){
      updatePlantBrand(
          plantInfoId:$plantInfoId,
          plantId:$plantId,
          brandId:$brandId,){
        brands{
          plantBrandId
        }
      }
    }