# Generated by Django 2.2.2 on 2019-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('country_region', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100, unique=True)),
                ('country_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('country_language', models.CharField(blank=True, max_length=100, null=True)),
                ('country_status', models.BooleanField(blank=True, null=True)),
                ('country_creation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
