# Generated by Django 2.2.2 on 2019-09-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_unit', '0001_initial'),
        ('brands', '0003_remove_brands_bus_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Brands',
            fields=[
                ('plant_brand_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_brand_status', models.BooleanField(blank=True, null=True)),
                ('plant_brand_creation', models.DateField(blank=True, null=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brands')),
                ('prod_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_unit.Business_Unit')),
            ],
            options={
                'db_table': 'plant_brands',
                'managed': True,
            },
        ),
    ]
