# Generated by Django 2.2.2 on 2019-09-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_brands', '0002_plant_brands_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_brands',
            name='prod_category_id',
        ),
    ]
