# Generated by Django 2.2.2 on 2019-09-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0001_initial'),
        ('plant_brands', '0003_remove_plant_brands_prod_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_brands',
            name='product_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_unit.Business_Unit'),
        ),
    ]
