# Generated by Django 2.2.2 on 2019-09-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_brands', '0004_plant_brands_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_brands',
            name='product_category_id',
        ),
    ]
