# Generated by Django 2.2.2 on 2019-08-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_status', models.BooleanField()),
                ('city_creation', models.DateField()),
                ('city_county_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='county.County')),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
    ]
