# Generated by Django 2.2.2 on 2019-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Certificates', '0003_certificates_certs_info_series'),
        ('plant_information', '0006_remove_plant_information_brand_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Certificates',
            fields=[
                ('plant_cert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_cert_status', models.BooleanField(blank=True, null=True)),
                ('plant_cert_creation', models.DateField(blank=True, null=True)),
                ('certificate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Certificates.Certificates')),
                ('plant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_information.Plant_Information')),
            ],
            options={
                'db_table': 'plant_certificates',
                'managed': True,
            },
        ),
    ]
