# Generated by Django 2.2.2 on 2019-08-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_contacts',
            name='plant_cont_phone_2',
            field=models.IntegerField(null=True),
        ),
    ]
