# Generated by Django 2.2.2 on 2019-08-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_contacts', '0002_plant_contacts_plant_cont_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_contacts',
            name='plant_cont_supp_lang_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_contacts',
            name='plant_cont_supp_lang_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_contacts',
            name='plant_cont_supp_lang_3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_contacts',
            name='plant_cont_supp_lang_4',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
