FROM python:3

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

# EXPOSE port to be used
#EXPOSE 8000

# Set command to run as soon as container is up
#CMD python manage.py runserver 0000:8000 --settings=backend.settings.dev