version: '3.3'

volumes: 
  pgdata:

services:
  neoweb:
    image: projectneo.azurecr.io/neo
    build:
      context: .
    volumes:
      - .:/usr/src
    ports: 
      - 8000:8000
    command: gunicorn -b 0.0.0.0:8000 backend.wsgi:application
    env_file: 
      - ./.env
  postgres:
    image: postgres
    env_file: 
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - ./backend/media/:/usr/src/media/
      - ./backend/staticfiles/:/usr/src/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/sites-enabled/

  
