FROM python:3.7

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR '/usr/src/app'

COPY ./requirements.txt .

RUN pip install -r requirements.txt

# EXPOSE port to be used
COPY . .
EXPOSE 8000

# Set command to run as soon as container is up
CMD python manage.py runserver 0.0.0.0:8000