version: '3.3'

volumes:
    postgres_data: {}
services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    restart: on-failure
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/usr/src/app
    ports: 
      - 8000:8000
    depends_on:
      - postgres    
    restart: on-failure
    env_file: .env
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./staticfiles/:/staticfiles/
  #     - ./nginx/default.conf:/etc/nginx/default.conf:ro
  # frontend:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app/
  #     - ./app/frontend/node_modules    
  #   restart: on-failure

  
