# Generated by Django 2.2.2 on 2019-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certs_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certs_info_title', models.CharField(max_length=250, unique=True)),
                ('certs_info_type', models.CharField(max_length=100)),
                ('certs_info_category', models.CharField(max_length=100)),
                ('certs_info_expire_date', models.DateTimeField()),
                ('certs_info_link', models.CharField(max_length=300)),
                ('certs_info_score', models.IntegerField()),
                ('certs_info_language', models.CharField(max_length=100)),
                ('certs_info_docu_no', models.CharField(max_length=100)),
                ('certs_info_publish_date', models.DateTimeField()),
                ('certs_info_status', models.BooleanField()),
                ('certs_info_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Certificates',
                'managed': True,
            },
        ),
    ]
