# Generated by Django 2.2.2 on 2019-09-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificates',
            table='certificates',
        ),
    ]
