# Generated by Django 2.2.2 on 2019-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0002_auto_20190903_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certs_info_series',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
