# Generated by Django 2.2.2 on 2019-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_auto_20190814_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
