# Generated by Django 2.2.2 on 2019-08-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Functions',
            fields=[
                ('plant_func_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_func_machining', models.BooleanField(null=True)),
                ('plant_func_painting', models.BooleanField(null=True)),
                ('plant_func_heat_treat', models.BooleanField(null=True)),
                ('plant_func_welding', models.BooleanField(null=True)),
                ('plant_func_hydro', models.BooleanField(null=True)),
                ('plant_func_functional_testing', models.BooleanField(null=True)),
                ('plant_func_radiograph', models.BooleanField(null=True)),
                ('plant_func_ultrasonic', models.BooleanField(null=True)),
                ('plant_func_penetrant', models.BooleanField(null=True)),
                ('plant_func_mag_particle', models.BooleanField(null=True)),
                ('plant_func_visual', models.BooleanField(null=True)),
                ('plant_func_capacity_per', models.IntegerField(null=True)),
                ('plant_func_product_listing', models.CharField(max_length=150, null=True)),
                ('plant_info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_information.Plant_Information')),
            ],
            options={
                'db_table': 'plant_functions',
                'managed': True,
            },
        ),
    ]
