# Generated by Django 2.2.2 on 2019-08-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_group', '0002_auto_20190822_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brands_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brands_name', models.CharField(max_length=120)),
                ('brands_markets', models.TextField()),
                ('brands_add_info', models.TextField()),
                ('brands_code', models.CharField(max_length=120)),
                ('brands_status', models.BooleanField(blank=True, null=True)),
                ('brands_creation', models.DateField(blank=True, null=True)),
                ('bus_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_group.Business_Group')),
            ],
            options={
                'db_table': 'brands',
                'managed': True,
            },
        ),
    ]
