# Generated by Django 2.2.2 on 2019-08-21 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant_contacts', '0002_plant_contacts_plant_cont_phone_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Information',
            fields=[
                ('plant_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_info_name', models.CharField(max_length=150)),
                ('plant_info_hrs_operation', models.CharField(max_length=150, null=True)),
                ('plant_info_phone_no', models.IntegerField(null=True)),
                ('plant_info_phone_no_sales', models.IntegerField(null=True)),
                ('plant_info_phone_no_support', models.IntegerField(null=True)),
                ('plant_info_phone_after_office_hrs', models.IntegerField(null=True)),
                ('plant_info_email_address', models.CharField(max_length=150, null=True)),
                ('plant_info_add_info', models.CharField(max_length=150, null=True)),
                ('plant_info_website', models.CharField(max_length=150, null=True)),
                ('plant_info_online_seller_site', models.CharField(max_length=150, null=True)),
                ('plant_info_contact_form', models.CharField(max_length=150, null=True)),
                ('plant_info_status', models.BooleanField(null=True)),
                ('plant_info_request_qoute', models.CharField(max_length=150, null=True)),
                ('plant_info_head_count', models.IntegerField(null=True)),
                ('plant_info_square_ft', models.IntegerField(null=True)),
                ('plant_info_num_shifts', models.IntegerField(null=True)),
                ('plant_info_certifications', models.CharField(max_length=150, null=True)),
                ('plant_info_QA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_info_QA', to='plant_contacts.Plant_Contacts')),
                ('plant_info_site_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_info_site_leader', to='plant_contacts.Plant_Contacts')),
            ],
            options={
                'db_table': 'plant_information',
                'managed': True,
            },
        ),
    ]
