# Generated by Django 2.2.2 on 2019-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_information',
            name='plant_info_production',
            field=models.IntegerField(null=True),
        ),
    ]
