# Generated by Django 2.2.2 on 2019-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_remove_brands_bus_unit'),
        ('plant_information', '0004_auto_20190902_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_information',
            name='brand_ids',
            field=models.ManyToManyField(related_name='brand_ids', to='brands.Brands'),
        ),
    ]
