# Generated by Django 2.2.2 on 2019-08-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant_contacts', '0002_plant_contacts_plant_cont_phone_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Contact_Type',
            fields=[
                ('plant_contact_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CW_sales_distribution', models.BooleanField()),
                ('CW_service_support', models.BooleanField()),
                ('CW_training_centers', models.BooleanField()),
                ('CW_plants', models.BooleanField()),
                ('CW_innovation_centers', models.BooleanField()),
                ('CT_global_headquarters', models.BooleanField()),
                ('CT_emerson', models.BooleanField()),
                ('CT_country_headquarters', models.BooleanField()),
                ('CT_local_bus_partner', models.BooleanField()),
                ('CT_retailer', models.BooleanField()),
                ('CT_distri_wholesaler', models.BooleanField()),
                ('CT_contractor', models.BooleanField()),
                ('CT_online_seller', models.BooleanField()),
                ('CT_sales_office', models.BooleanField()),
                ('CT_sales_rep', models.BooleanField()),
                ('CT_tech_support', models.BooleanField()),
                ('CT_customer_service', models.BooleanField()),
                ('CT_service_center', models.BooleanField()),
                ('CT_training_center', models.BooleanField()),
                ('CT_plant', models.BooleanField()),
                ('CT_helix', models.BooleanField()),
                ('shown_on_contact_us', models.BooleanField()),
                ('shown_on_where_to_buy', models.BooleanField()),
                ('plant_contact_type_status', models.BooleanField()),
                ('plant_cont_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_contacts.Plant_Contacts')),
            ],
            options={
                'db_table': 'plant_contact_type',
                'managed': True,
            },
        ),
    ]
