# Generated by Django 2.2.2 on 2019-08-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Group',
            fields=[
                ('bus_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus_group_name', models.CharField(max_length=120)),
                ('bus_group_code', models.CharField(max_length=20)),
                ('bus_group_status', models.BooleanField(blank=True, null=True)),
                ('bus_group_creation', models.DateField(blank=True, null=True)),
                ('bus_plat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_platform.Business_Platform')),
            ],
            options={
                'db_table': 'business_group',
                'managed': True,
            },
        ),
    ]
