# Generated by Django 2.2.2 on 2019-08-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state_province', '0001_initial'),
        ('zip_code', '0001_initial'),
        ('county', '0003_auto_20190814_1705'),
        ('city', '0002_auto_20190814_1525'),
        ('country', '0001_initial'),
        ('plant_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Location',
            fields=[
                ('plant_loc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_loc_latitude', models.FloatField()),
                ('plant_loc_longitude', models.FloatField()),
                ('plant_loc_address', models.CharField(max_length=150)),
                ('plant_loc_map', models.CharField(max_length=150)),
                ('plant_loc_status', models.BooleanField()),
                ('plant_info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_information.Plant_Information')),
                ('plant_loc_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_loc_city', to='city.City')),
                ('plant_loc_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_loc_country', to='country.Country')),
                ('plant_loc_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_loc_county', to='county.County')),
                ('plant_loc_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_loc_state', to='state_province.StateProvince')),
                ('plant_loc_zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_loc_zipcode', to='zip_code.ZipCode')),
            ],
            options={
                'db_table': 'plant_location',
                'managed': True,
            },
        ),
    ]
