# Generated by Django 2.2.2 on 2019-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_location', '0002_auto_20190828_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_location',
            name='plant_loc_county',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
