# Generated by Django 2.2.2 on 2019-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_location', '0003_auto_20190903_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_location',
            name='plant_loc_state',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
