# Generated by Django 2.2.2 on 2019-08-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_contact_type', '0002_plant_contact_type_plant_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_contact_type',
            name='plant_cont_id',
        ),
    ]
