# Generated by Django 2.2.2 on 2019-08-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('county', '0003_auto_20190814_1705'),
        ('country', '0001_initial'),
        ('zip_code', '0001_initial'),
        ('state_province', '0001_initial'),
        ('city', '0002_auto_20190814_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
                ('address_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='county.County')),
                ('address_state_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state_province.StateProvince')),
                ('address_zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zip_code.ZipCode')),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
    ]
