# Generated by Django 2.2.2 on 2019-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_information', '0003_plant_information_plant_info_eng_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_add_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_certifications',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_contact_form',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_email_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_eng_tech',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_head_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_hrs_operation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_num_shifts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_online_seller_site',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_phone_after_office_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_phone_no_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_phone_no_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_request_qoute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_square_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='plant_info_website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
