# Generated by Django 2.2.2 on 2019-08-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0003_auto_20190823_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Certs',
            new_name='prod_item_list_Certs',
        ),
    ]
