# Generated by Django 2.2.2 on 2019-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0004_auto_20190823_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_list_Certs',
            field=models.TextField(),
        ),
    ]
