# Generated by Django 2.2.2 on 2019-08-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0005_auto_20190823_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Crit_Service',
            new_name='prod_item_crit_service',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Features',
            new_name='prod_item_features',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Flow_Char',
            new_name='prod_item_flow_char',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_list_Certs',
            new_name='prod_item_list_certs',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Material',
            new_name='prod_item_material',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Opt_Temp',
            new_name='prod_item_opt_temp',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Other_Config',
            new_name='prod_item_other_config',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Press_Class',
            new_name='prod_item_press_class',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Proc_Conn_Type',
            new_name='prod_item_proc_conn_type',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Shutoff_Class',
            new_name='prod_item_shutoff_class',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Valve_Size',
            new_name='prod_item_valve_size',
        ),
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_Valve_Size_Standard',
            new_name='prod_item_valve_size_standard',
        ),
    ]
