# Generated by Django 2.2.2 on 2019-08-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0006_auto_20190823_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_crit_service',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_flow_char',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_opt_temp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_other_config',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_press_class',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_proc_conn_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_shutoff_class',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_valve_size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_item',
            name='prod_item_valve_size_standard',
            field=models.TextField(),
        ),
    ]
