# Generated by Django 2.2.2 on 2019-08-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0007_auto_20190823_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_item',
            old_name='prod_item_list_certs',
            new_name='prod_item_certs',
        ),
    ]
