# Generated by Django 2.2.2 on 2019-08-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_item', '0008_auto_20190823_1723'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products_item',
            table='products_item',
        ),
    ]
