# Generated by Django 2.2.2 on 2019-08-09 15:52

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('state_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state_status', models.BooleanField(blank=True, null=True)),
                ('state_creation', models.DateField(blank=True, null=True)),
                ('state_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'db_table': 'state_province',
                'managed': True,
            },
        ),
    ]
