# Generated by Django 2.2.2 on 2019-09-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_product_category', '0002_brand_prod_cat_plant_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_prod_cat',
            name='plant_ids',
        ),
    ]
