# Generated by Django 2.2.2 on 2019-08-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_auto_20190814_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipcode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zipcode_number', models.IntegerField()),
                ('zipcode_status', models.BooleanField()),
                ('zipcode_creation', models.DateField()),
                ('zipcode_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.City')),
            ],
            options={
                'db_table': 'zip_code',
                'managed': True,
            },
        ),
    ]
